name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:
  # schedule:
  #   - cron: 0 0 * * *

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  falafel:
    runs-on: ubuntu-latest
    env:
      PUBLIC_ATPROTO_DID: ${{ vars.PUBLIC_ATPROTO_DID }}
      PUBLIC_ATPROTO_PUBLICATION_RKEY: ${{ vars.PUBLIC_ATPROTO_PUBLICATION_RKEY }}
      ATPROTO_SERVICE: ${{ secrets.ATPROTO_SERVICE }}
      ATPROTO_APP_PASSWORD: ${{ secrets.ATPROTO_APP_PASSWORD }}
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      GOOGLE_MAPS_LIST_PB: ${{ secrets.GOOGLE_MAPS_LIST_PB }}

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v6

      - name: Setup PNPM
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          version: 10.13.1
          package_json_file: "./package.json"

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: Install pnpm
        shell: bash
        working-directory: .
        run: pnpm install

      - name: test vars
        shell: bash
        working-directory: .
        run: npx tsx ./scripts/testVars.ts

  build:
    runs-on: ubuntu-latest
    env:
      PUBLIC_ATPROTO_DID: ${{ vars.PUBLIC_ATPROTO_DID }}
      PUBLIC_ATPROTO_PUBLICATION_RKEY: ${{ vars.PUBLIC_ATPROTO_PUBLICATION_RKEY }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v6
      - name: Install, build, and upload your site
        uses: withastro/action@v6

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
