name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  # schedule:
  #   - cron: 0 0 * * *

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUBLIC_ATPROTO_DID: ${{ vars.PUBLIC_ATPROTO_DID }}
      PUBLIC_ATPROTO_PUBLICATION_RKEY: ${{ vars.PUBLIC_ATPROTO_PUBLICATION_RKEY }}
    steps:
      - name: Print from env
        run: echo "$PUBLIC_ATPROTO_DID and $PUBLIC_ATPROTO_PUBLICATION_RKEY"
      - name: Print from vars directly
        run: echo "${{ vars.PUBLIC_ATPROTO_DID }} and ${{ vars.PUBLIC_ATPROTO_PUBLICATION_RKEY }}"
      - name: Checkout your repository using git
        uses: actions/checkout@v6
      - name: Install, build, and upload your site
        uses: withastro/action@v6

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5